// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_COLORS_H
#define PICOPIXEL_LVGL_UI_COLORS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Common colors
extern const uint32_t common_000000;
extern const uint32_t common_111111;
extern const uint32_t common_1db954;
extern const uint32_t common_ffffff;

#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_COLORS_H*/
