// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_SCREENS_H
#define PICOPIXEL_LVGL_UI_SCREENS_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _objects_t {
    lv_obj_t *screen_1;
    lv_obj_t *main_container;
    lv_obj_t *label_1;
    lv_obj_t *connect_to_spotify;
    lv_obj_t *textarea_1;
    lv_obj_t *status;
    lv_obj_t *connect_to_spotify_label;
} objects_t;

extern objects_t objects;

enum ScreensEnum {
    SCREEN_ID_SCREEN_1 = 1,
};

void create_screen_screen_1();
void tick_screen_screen_1();
void delete_screen_screen_1();

void tick_screen_by_id(enum ScreensEnum screenId);
void tick_screen(int screen_index);

void delete_screen_by_id(enum ScreensEnum screenId);

void create_screens();


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_SCREENS_H*/
