// Generated by PicoPixel.io — https://picopixel.io
/**
 * @file fonts.c
 * @brief Custom font lookup for LVGL UI
 *
 * Each font .c file is compiled separately.
 */

#include "fonts.h"
#include <string.h>

const lv_font_t* ui_get_font_by_name(const char* name) {
    if (name == NULL) return NULL;
    if (strcmp(name, "font_dm_sans_14") == 0) return &font_dm_sans_14;
    if (strcmp(name, "font_dm_sans_700_16") == 0) return &font_dm_sans_700_16;
    return NULL;
}
